CREATE TABLE USUARIO 
(
  ID INT NOT NULL 
, CPF INT NOT NULL 
, NOME VARCHAR2(20) NOT NULL 
, EMAIL VARCHAR2(20) NOT NULL 
, LOGIN VARCHAR2(20) NOT NULL 
, SENHA VARCHAR2(20) NOT NULL 
, CONSTRAINT USUARIO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
)

SELECT * FROM USUARIO